#!groovy
pipeline {
    agent {
        docker {
            image 'android-otus'
            args '-it --memory=12g --cpus=8 -e PASSPHRASE=${PASSPHRASE}'
        }
    }
    stages {
        stage("init") {
            steps {
                sh "chmod +x ci/prepare_container.sh"
                sh "ci/prepare_container.sh"
                prepareProp()
                sh "./gradlew"
            }
        }
        stage("build") {
            steps {
                sh "./gradlew app:assembleDebug"
            }
        }
        stage("deploy") {
            steps {
                archiveArtifacts(artifacts: "app/build/**", allowEmptyArchive: true)
            }
        }
    }
    post {
       success{
            sh "echo 'success'"
       }
       failure{
            sh "echo 'failure'"
       }
    }
}

def prepareProp {
    def propPath = "/.keystore/"
    sh "mkdir -p ${env.HOME}${propPath}"
    withCredentials([file(credentialsId: 'prop', variable: 'prop')]) {
        sh "cp -f ${keystore} ${env.HOME}${propPath}properties."
    }
    withCredentials([file(credentialsId: 'keystore', variable: 'keystore')]) {
        sh "cp -f ${keystore} ${env.HOME}${propPath}keystore.jks"
    }
}